### ISSUE TITLE
Modal projects

### ISSUE THREAD

**Issue by Azlou77** [Azlou77/JS-Node-projects#29]
what is a modal ❓ 
- A modal is an element that when you touch that open up 
  a form with several fields like name, email, password for example
  when you have a connexion.

**part HTML:**
- create an hero section
- create button modal
- add script modal.js

**part CSS:**
- /* The Modal (background) */
- /* Modal Content/Box */
- /* The Close Button */

**part  JS:**
- get elements by id
- get the element by class
- onclick add open or close events

**Notions:**
-  **data-bs-toggle**="modal": 
-  **data-bs-target**="#exampleModal"
L'attribut data-toggle contient le type d'événement qui va être lié à un bouton 

![Image](https://github.com/Azlou77/JS-Node-projects/assets/69016056/a16da9b7-5d83-46ce-8db4-4e74754ceded)

**Comment by yannmarc** [comment]
Hi @Azlou77 can I assist in this issue?
